#!/usr/bin/env php
<?php

include __DIR__ . "/vendor/autoload.php";

define('ROOT_PATH', __DIR__);
define('LOG_PATH', ROOT_PATH . '/logs');
define('COMMAND_PATH', ROOT_PATH . '/app/Console');

$dotenv = new Symfony\Component\Dotenv\Dotenv();
$dotenv->load('.env');

$application = new Symfony\Component\Console\Application();

foreach (scandir(COMMAND_PATH) as $file):
    if (preg_match('#\.php$#', $file)) {
        $className = 'App\Console\\' . preg_replace('#^(.*)(\.php)$#', '$1', $file);
        $application->add(new $className);
    }
endforeach;

$status = $application->run();

exit($status);